version: '3.5'
services:
  api-postgres:
    container_name: api-postgres
    build: .
    ports:
      - 4000:4000
    environment:
      PORT: 4000

  web-client:
    container_name: web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
